### PR TITLE
Add Fedora, Enterprise Linux

### PR DESCRIPTION
**Pull request by ppfeister**

### CODE REVIEW

**Comment by ppfeister** [comment]
Do not merge. Remaining as draft while package is in review and in testing.

**Comment by ppfeister** [comment]
This can now be merged, now that Sherlock is in stable @sdushantha 
Marking as ready for review

**Comment by ppfeister** [comment]
Actually, let me make a tweak.

**Comment by ppfeister** [comment]
GTG.

**Comment by sdushantha** [comment]
Looks like I broke this PR attempting to change the author of the commits you had made. The reason for changing the author is because we only have the free tier and Mintlfy wont bulid the code if another person commits

**Comment by sdushantha** [comment]
trying to reopen

**Comment by sdushantha** [comment]
Looks like its broken
image

**Comment by ppfeister** [comment]
Well that's a new one
I'll just recommit with you as the author and force push to this branch

You don't sign your commits so it should be no different

**Pull request closed without merging**
